name: Python Library Test and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  deployments: write
  packages: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        # token: ${{ secrets.GH_TOKEN }}
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest wheel python-semantic-release
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest test.py
    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        repository_username: __token__
        repository_password: ${{ secrets.PYPI_TOKEN }}
    # - name: Publish to PyPi
    #   env:
    #     TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
    #     TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    #   run: |
    #     python -m build
    #     python -m twine upload --repository testpypi dist/*